version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=william
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=api-rest-adonis
      - TZ=GMT
    volumes:
      - "./db-posgres/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
